import React, { useState, useEffect } from 'react';
import { Upload, FileText, CheckCircle, Database, Server, RefreshCw } from 'lucide-react';
import { colmapAPI } from '../utils/api';

export function ColmapUploader({ onColmapLoaded, currentData }) {
  const [loading, setLoading] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const [jsonText, setJsonText] = useState('');

  useEffect(() => {
    async function loadCurrentTransforms() {
      try {
        const res = await fetch('/transforms.json');
        if (res.ok) {
          const text = await res.text();
          setJsonText(text);
        }
      } catch (e) {
        console.warn("Could not load /transforms.json in editor:", e);
      }
    }
    loadCurrentTransforms();
  }, []);

  const handleFileUpload = async (file) => {
    if (!file) return;
    setLoading(true);
    try {
      const content = await file.text();
      setJsonText(content);
      const summary = await colmapAPI.uploadFile(file);
      const candidates = await colmapAPI.extractCandidates(JSON.parse(content));
      onColmapLoaded(summary, candidates);
    } catch (e) {
      alert("Error parsing file: " + e.message);
    } finally {
      setLoading(false);
    }
  };

  const handleProcessRawJSON = async () => {
    setLoading(true);
    try {
      const parsed = JSON.parse(jsonText);
      const summary = await colmapAPI.processJSON(parsed);
      const candidates = await colmapAPI.extractCandidates(parsed);
      onColmapLoaded(summary, candidates);
    } catch (e) {
      alert("Invalid JSON data: " + e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6 overflow-y-auto max-h-full">
      <div className="flex items-center justify-between border-b border-cyber-border pb-4">
        <div>
          <h2 className="text-xl font-extrabold tracking-wide uppercase text-slate-100 flex items-center gap-2">
            <Database className="w-5 h-5 text-cyber-accent" />
            COLMAP Photogrammetry Data Processor
          </h2>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Ingest transforms.json camera extrinsics and intrinsics generated by COLMAP / Instant-NGP / Nerfstudio
          </p>
        </div>
        <button
          onClick={handleProcessRawJSON}
          disabled={loading}
          className="flex items-center space-x-2 bg-cyber-accent text-cyber-dark px-4 py-2 rounded-lg font-bold text-xs hover:brightness-110 transition-all shadow-lg glow-accent"
        >
          {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Server className="w-4 h-4" />}
          <span>PROCESS DATASET</span>
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Upload Drop Zone */}
        <div
          onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
          onDragLeave={() => setDragActive(false)}
          onDrop={(e) => {
            e.preventDefault();
            setDragActive(false);
            if (e.dataTransfer.files?.[0]) handleFileUpload(e.dataTransfer.files[0]);
          }}
          className={`glass-panel border-2 border-dashed rounded-xl p-8 flex flex-col items-center justify-center text-center transition-all ${
            dragActive ? 'border-cyber-accent bg-cyber-accent/10' : 'border-cyber-border hover:border-slate-500'
          }`}
        >
          <div className="w-14 h-14 rounded-full bg-cyber-accent/10 flex items-center justify-center mb-4">
            <Upload className="w-7 h-7 text-cyber-accent" />
          </div>
          <h3 className="font-bold text-sm text-slate-200">Drag & Drop transforms.json Here</h3>
          <p className="text-xs text-slate-400 mt-1 mb-4">Supports standard COLMAP / NeRF JSON format</p>

          <label className="cursor-pointer bg-slate-800 hover:bg-slate-700 text-slate-200 px-4 py-2 rounded-lg text-xs font-semibold border border-cyber-border transition-all">
            <span>Browse Computer</span>
            <input
              type="file"
              accept=".json"
              className="hidden"
              onChange={(e) => e.target.files?.[0] && handleFileUpload(e.target.files[0])}
            />
          </label>
        </div>

        {/* JSON Code Editor / Quick Preview */}
        <div className="glass-panel rounded-xl p-4 flex flex-col">
          <div className="flex items-center justify-between text-xs font-mono text-slate-400 mb-2">
            <span className="flex items-center gap-1">
              <FileText className="w-4 h-4 text-cyber-accent" />
              transforms.json Payload Editor
            </span>
            <span className="text-cyber-success text-[11px]">JSON ACTIVE</span>
          </div>
          <textarea
            value={jsonText}
            onChange={(e) => setJsonText(e.target.value)}
            className="w-full flex-1 bg-cyber-dark font-mono text-xs text-cyber-accent p-3 rounded-lg border border-cyber-border focus:outline-none focus:border-cyber-accent focus:ring-1 focus:ring-cyber-accent resize-none min-h-[220px]"
          />
        </div>
      </div>

      {/* Extracted Stats Summary Card */}
      {currentData && (
        <div className="glass-panel p-5 rounded-xl border border-cyber-accent/30 space-y-4">
          <h3 className="text-xs font-mono font-bold text-cyber-accent uppercase tracking-wider flex items-center gap-2">
            <CheckCircle className="w-4 h-4 text-cyber-success" />
            Active COLMAP Photogrammetry Metadata
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs font-mono">
            <div className="bg-cyber-dark/60 p-3 rounded-lg border border-cyber-border">
              <span className="text-slate-400 block text-[10px]">TOTAL CAMERA POSES</span>
              <span className="text-lg font-bold text-slate-100">{currentData.frame_count} Frames</span>
            </div>
            <div className="bg-cyber-dark/60 p-3 rounded-lg border border-cyber-border">
              <span className="text-slate-400 block text-[10px]">FOCAL LENGTH (FL_X)</span>
              <span className="text-lg font-bold text-cyber-accent">{currentData.camera_intrinsics?.fl_x || '847.63'} px</span>
            </div>
            <div className="bg-cyber-dark/60 p-3 rounded-lg border border-cyber-border">
              <span className="text-slate-400 block text-[10px]">SENSOR RES (W x H)</span>
              <span className="text-lg font-bold text-slate-100">
                {currentData.camera_intrinsics?.w || 1080} x {currentData.camera_intrinsics?.h || 1920}
              </span>
            </div>
            <div className="bg-cyber-dark/60 p-3 rounded-lg border border-cyber-border">
              <span className="text-slate-400 block text-[10px]">FIELD OF VIEW (FOV)</span>
              <span className="text-lg font-bold text-cyber-success">65.0°</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
